[package]
name = "wasm_canvas_animate_solar_system"
version = "1.0.0"
authors = ["Vladimir Iftodi <Vladimir.Iftodi@gmail.com>"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm_val = "0.3.5"
lazy_static = "1.0.2"