[package]
name = "wasm_create_element"
version = "1.0.0"
authors = ["Vladimir Iftodi <Vladimir.Iftodi@gmail.com>"]

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm_val = "0.3.5"